version: '3'

services:
    db:
        build: ./db
        networks:
            - core
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
    apparel:
        build: ./apparel
        networks:
            - core
        volumes:
            - ./apparel:/app
        depends_on:
            - db
        ports:
            - 5001:80
    prices:
        build: ./prices
        networks:
            - core
            - site
        volumes:
            - ./prices:/app
        ports:
            - 5002:80
        depends_on:
            - apparel
    site:
        build: ./site
        networks:
            - site
        volumes:
            - ./site:/src
        ports:
            - 5000:80
        depends_on: 
            - prices
networks:
    core:
        driver: bridge
    site:
        driver: bridge